### ISSUE TITLE
consult for code

### ISSUE THREAD

**Issue by chouqin3** [abhi1kumar/MERL-RAV_dataset#1]
Thanks. Great work it is!
Could you share your codes completely in order to help us to understand?

**Comment by abhi1kumar** [comment]
I assume that you are talking about the codes of our CVPR paper. The code approval is pending from the MERL authorities and once it gets approved, we would be releasing it.

**Comment by starhiking** [comment]
> I assume that you are talking about the codes of our CVPR paper. The code approval is pending from the MERL authorities and once it gets approved, we would be releasing it.

Thanks. 
I wanna to know how to train in WFLW or 300W, Does it need relabel the visiblity value like MERL-RAV?

**Comment by abhi1kumar** [comment]
No, WFLW or 300W do not label visibility. WFLW labels self-occluded landmarks as if they were located on the visible boundary of the noseless face while 300-W does not have profile faces and therefore does not have any self-occluded landmarks. The datasets are summarized in Table 1 of our [paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Kumar_LUVLi_Face_Alignment_Estimating_Landmarks_Location_Uncertainty_and_Visibility_Likelihood_CVPR_2020_paper.pdf) while details can be found in its Section 4.

For training on WFLW or 300-W, the landmarks are all visible and therefore, models trained on these datasets can not do visibility classification. Our [demo](https://www.cse.msu.edu/computervision/kumar_marks_mou_wang_jones_cherian_akino_liu_feng_cvpr2020.mp4) therefore uses model trained on MERL-RAV dataset and not trained on 300-W or AFLW-19 or WFLW.

**Comment by abhi1kumar** [comment]
> I assume that you are talking about the codes of our CVPR paper. The code approval is pending from the MERL authorities and once it gets approved, we would be releasing it.

 The codebase is now publicly available [here](https://github.com/abhi1kumar/LUVLi).

**Comment by timmmer** [comment]
Hi Abhinav,

Happy New Year!

MERL is only allowed to release the code through MERL’s website, not through github.

Please remove the code from github ASAP, and point people to this location to download the code from MERL:

https://www.merl.com/research/license/LUVLi

Best,
Tim
